---
name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

env: 
  MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: echo mongodb uri
        run: echo $env.MONGODB_URI

...